apiVersion: v1
kind: ServiceAccount
metadata:
  name: container-manager-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: container-manager-role
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: container-manager-rolebinding
subjects:
- kind: ServiceAccount
  name: container-manager-sa
roleRef:
  kind: Role
  name: container-manager-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: container-manager
spec:
  selector:
    matchLabels:
      app: container-manager
  template:
    metadata:
      labels:
        app: container-manager
    spec:
      serviceAccountName: container-manager-sa
      containers:
      - name: manager
        image: container-manager:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080